name: Benchmark

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions: {}

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for OIDC authentication with CodSpeed
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-rust@3d6fb132fbe7cdcb66bf8ec193911c2945369d12 # v1.0.17
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          tools: cargo-codspeed

      - name: Build Benchmark
        run: cargo codspeed build --features codspeed

      - name: Run benchmark
        uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4.18.5
        with:
          mode: simulation
          run: cargo codspeed run
